spring:
  liquibase:
    enabled: true
  jpa:
    properties:
      hibernate:
        default_schema: user-service
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: postgres
    password: postgres
